### ISSUE TITLE
Integration with mcmmo party!

### ISSUE THREAD

**Issue by xion87** [cybertiger/Bukkit-Instances#32]
can you use mcmmo party instead of separate party module?

**Comment by zerafox** [comment]
This would be great, if it could use McMMO parties for Instances. We use McMMO parties on my server as well, and the idea of having to have two separate parties to do two different things entirely is just silly in my opinion.
Would be great if it could hook into McMMO and use it's party system if we wanted it to.

**Comment by cybertiger** [comment]
McMMO parties provides no API for other plugins to receive notifications on party's being deleted, which means there's no way to know when an instance can be safely deleted, which makes this impossible to support.

**Comment by zerafox** [comment]
But instances are deleted when players are all out of it, not when the party disbands already.
Why would McMMO's parties be any different there?
