### ISSUE TITLE
Support to Heroes' parties [suggestion]

### ISSUE THREAD

**Issue by Joager** [cybertiger/Bukkit-Instances#46]
Right now the player needs to enter two parties to succeed: Heroes parties and Instances parties. Heroes has a full-fledged API and has some awesome addons already (ArathosRPG for example creates two additional slots for you to use items and has lores compatible with heroes like mana, spellpower and even critical magic chance!). it's the perfect plugin to use this addon with to create an awesome mmorpg. A nice support to it would be... more than nice, definetly awesome.

**Comment by cybertiger** [comment]
Heroes has no public API, nor is it open source.
