### ISSUE TITLE
Make spawners disable after spawning a certain amount of mobs [suggestion]

### ISSUE THREAD

**Issue by hejdu32** [cybertiger/Bukkit-Instances#49]
So as the title says, it would be lovely to be able to make a spawner disable after lets say 4 mobs have spawned / or 4 mobs have died.

This would be really usefull in instances with a fixed amount of mobs to kill. Like if you use it together with Quests you could make the spawners only spawn a fixed amount of monster, so that you would have to clear the entire instance in order to complete the quest.

Note that the spawner would only disable the spawner in the instance world.

**Comment by cybertiger** [comment]
Not possible, the spawner command uses only things which can be done with vanilla spawners.
