### ISSUE TITLE
Feature Request: Instances persistence across server restarts

### ISSUE THREAD

**Issue by OriginalMadman** [cybertiger/Bukkit-Instances#59]
instances are always deleted on server shutdown (which is problematic for persistence in this unstable age, to say the least). Can we please have that at least as a configurable choice true/false?

The same should be for parties, across logins and reboots.

Thanks!

**Comment by cybertiger** [comment]
I don't use this plugin, whilst it's a good idea and I'd love to add it, I just don't have time to do it.

Right now I'm only fixing bugs in this plugin.
