### ISSUE TITLE
EpicBossRecoded

### ISSUE THREAD

**Issue by Scratch741** [cybertiger/Bukkit-Instances#60]
Hello! I've posted a comment below your plugin page. I've an issue that bosses from EpicBossRecoded aren't copied properly. They just turn into regular mobs and with other versions they doesn't even copy (only regular mobs does). Running 1.7.9 R2.0 Craftbukkit (even tested older versions). Do you think it would be an easy fix for that? Just to properly copy a modified entity. Thanks!

**Comment by cybertiger** [comment]
The problem is that epicboss stores the world name, and coordinates of all the spawners. As a workaround you could edit it's config file and copy all the settings to world-1, world-2 etc, then it would work.

I don't use this plugin, whilst it's a good idea and I'd love to add it, I just don't have time to do it.

Right now I'm only fixing bugs in this plugin.

**Comment by Scratch741** [comment]
I don't really want spawners in instances. I mean I just want to make a room (dungeon) and just summon (not via timers/spawners) an epicboss and than make room as an instance. Players just go in, fight with the boss and the only way to respawn in just to leave instance and than go in again.

I remember this was WORKING. But in earlier versions and they had problem with world deleting properly. Later it just copied only the "mob" and not modified boss. I guess some fix or workaround done that. You may remember me posting here a bug with it.

Well I know if it will takes time that you don't have, it's pointless to add support for an old plugin.
 
Nice idea with the workaround. Gonna try it, even it wasn't meant to resummon epicboss in instances.

Thanks and sorry for late reply.

**Comment by Scratch741** [comment]
Well, this workaround donesn't work. Made location and timer in Bossland-1 and the boss isn't spawning here. Hope some day you'll have a time to fix this issue. I love the idea since I discovered this plugin but it never worked properly for me.
