### ISSUE TITLE
Portals not working on KCauldron

### ISSUE THREAD

**Issue by lBoBl** [cybertiger/Bukkit-Instances#65]

**Comment by Badcholo** [comment]
Most players using KCauldron have this issue and they are not willing to fix it.
I have attempted in many ways to fix the issue but can not. Has anyone found anything like this to use?

**Comment by cybertiger** [comment]
Someone would need to explicitely add code for KCauldron to the plugin.
I don't have the knowledge or time to do this, the plugin is open source and I'm willing to help if anyone can find a developer willing to do it.
