### ISSUE TITLE
Compiling Instances

### ISSUE THREAD

**Issue by Scratch741** [cybertiger/Bukkit-Instances#69]
Hello. I did not found how could I contact you via PM.
I want to translate messages. So I downloaded your plugin from Github, translated what I needed and wanted to compile it. But when I do "mvn clean install" it throws an error with dependencies. How do I compile it?

**Comment by cybertiger** [comment]
Apparently compilation was broken, and I didn't notice because I had everything installed in my local repository.

This commit: https://github.com/cybertiger/Bukkit-Instances/commit/27a0d1152cb782d26ae1e69c122072a504596bc5
fixes it.

**Comment by Scratch741** [comment]
Thanks!
