### ISSUE TITLE
ispawner

### ISSUE THREAD

**Issue by t0xic1** [cybertiger/Bukkit-Instances#71]
When trying to create spawner with /ispawner  for any mob it generates says internal error using spigot 1.9.2 and newest instance build.

http://pastebin.com/H95Q4T9g

**Comment by t0xic1** [comment]
Would like if someone answered me :(

**Comment by cybertiger** [comment]
Intend to move the /ispawner stuff into it's own plugin rather than fix it as part of instances.

Sorry, I have other commitments than fixing bugs for free in my plugins, but I do appreciate bugs being reported, so thanks.
